### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by giuseppepaul** [almilo/webpack-bundle-report#2]
Hi, nice package - I've found it useful thank you. One thing.. I see the last commit fixed the documents, the issue with "wbr" "wrb". 

You might want to publish the update to NPM because the docs on there still contain the typo, it threw me for a minute there haha!

https://www.npmjs.com/package/webpack-bundle-report

Cheers
Giuseppe

**Comment by almilo** [comment]
Hi @giuseppepaul,

Thanks for the feedback. Already published!

cheers,
Alberto
